const AuthorActionTypes = {
  FETCH_ALL_AUTHORS_START: "FETCH_ALL_AUTHORS_START",
  FETCH_ALL_AUTHORS_SUCCESS: "FETCH_ALL_AUTHORS_SUCCESS",
  FETCH_ALL_AUTHORS_FAILURE: "FETCH_ALL_AUTHORS_FAILURE",
};
export default AuthorActionTypes;
