const AuthorActionTypes ={
    FETCH_AUTHOR_START: 'FETCH_AUTHOR_START',
    FETCH_AUTHOR_SUCCESS:'FETCH_AUTHOR_SUCCESS',
    FETCH_AUTHOR_FAILURE: 'FETCH_AUTHOR_FAILURE',
    INITIALIZE_AUTHOR_STATE: 'INITIALIZE_AUTHOR_STATE'

}
export default AuthorActionTypes;