const BookActionTypes ={
    TOGGLE_BOOK_HIDDEN: 'TOGGLE_BOOK_HIDDEN',
    FETCH_BOOK_START: 'FETCH_BOOK_START',
    FETCH_BOOK_SUCCESS:'FETCH_BOOK_SUCCESS',
    FETCH_BOOK_FAILURE: 'FETCH_BOOK_FAILURE',
    INITIALIZE_BOOK_STATE: 'INITIALIZE_BOOK_STATE'

}
export default BookActionTypes;