const BookActionTypes ={
    TOGGLE_BOOK_HIDDEN: 'TOGGLE_BOOK_HIDDEN',
    FETCH_BOOK_START: 'FETCH_BOOK_START',
    FETCH_BOOK_SUCCESS:'FETCH_BOOK_SUCCESS',
    FETCH_BOOK_FAILURE: 'FETCH_BOOK_FAILURE',
    INITIALIZE_BOOK_STATE: 'INITIALIZE_BOOK_STATE',
    FETCH_AUTHOR_START: 'FETCH_AUTHOR_START',
    FETCH_AUTHOR_SUCCESS:'FETCH_AUTHOR_SUCCESS',
    FETCH_AUTHOR_FAILURE: 'FETCH_AUTHOR_FAILURE',
    TOGGLE_DELETE_BOOK: 'TOGGLE_DELETE_BOOK',
    DELETE_BOOK :'DELETE_BOOK'
}
export default BookActionTypes;