const BookActionTypes ={
    TOGGLE_BOOK_HIDDEN: 'TOGGLE_BOOK_HIDDEN',
    FETCH_BOOK_START: 'FETCH_BOOK_START',
    FETCH_BOOK_SUCCESS:'FETCH_BOOK_SUCCESS',
    FETCH_BOOK_FAILURE: 'FETCH_BOOK_FAILURE'

}
export default BookActionTypes;